/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PatientPrescription;
import Doctor.about;
import Login.Login;
import java.awt.print.PrinterException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.lang.String.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
/**
 *
 * @author Haris
 */
public class PatientPrescription extends javax.swing.JFrame {

    /**
     * Creates new form PatientPrescription
     */
//    private static final String username="root";
//    private static final String password="root";
//    private static final String dataconn="jdbc:mysql://localhost:3306/patientprescription";
//    
//    Connection sqlcon=null;
//    PreparedStatement pst=null;
//    ResultSet rs=null;
//    int q,i,id,deleteitem;
    
    private JFrame frame;
    
    public PatientPrescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
////    ===============================UPDATE DB FUNCTION===========================================
//    
//    public void upDateDB(){
//        
//        try{
//            Class.forName("com.mysql.jdbc.Driver");
//            sqlcon=DriverManager.getConnection(dataconn,username,password);
//            pst=sqlcon.prepareStatement("select * from patientprescription");
//            
//            rs=pst.executeQuery();
//            ResultSetMetaData stData=rs.getMetaData();
//            
//            q=stData.getColumnCount();
//            
//            DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
//            RecordTable.setRowCount(0);
//            
//            while(rs.next()){
//                Vector columndata=new Vector();
//                
//                for(i=0;i<q;i++){
//                    columndata.add(rs.getString("id"));
//                    columndata.add(rs.getString("patientID"));
//                    columndata.add(rs.getString("MedName"));
//                    columndata.add(rs.getString("MedDose"));
//                    columndata.add(rs.getString("IssueDate"));
//                    columndata.add(rs.getString("ExpiryDate"));
//                    columndata.add(rs.getString("PatientName"));
//                    columndata.add(rs.getString("PatientDOB"));
//                    columndata.add(rs.getString("PatientPhoneNumber"));
//                }
//                RecordTable.addColumn(columndata);
//            }
//        }catch(ClassNotFoundException | SQLException e){
//            JOptionPane.showMessageDialog(null,e);
//        }
//    }
//    
////    =================================END DB FUNCTION============================================

    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnPrescription = new javax.swing.JButton();
        jbtnAddNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtMedName = new javax.swing.JTextField();
        jtxtMedDose = new javax.swing.JTextField();
        jtxtAppointment = new javax.swing.JTextField();
        jtxtFees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtPatientDOB = new javax.swing.JTextField();
        jtxtPatientMobNumber = new javax.swing.JTextField();
        jcmbMedType = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemReset = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Panel");
        setMinimumSize(new java.awt.Dimension(1078, 599));
        setPreferredSize(new java.awt.Dimension(1078, 599));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PATIENT PANEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane2.setViewportView(jtxtPrescription);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 340, 330));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientPrescription/icons8-exit-24.png"))); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientPrescription/icons8-clear-symbol-24.png"))); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientPrescription/icons8-delete-24.png"))); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientPrescription/icons8-print-24.png"))); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        jbtnPrescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientPrescription/icons8-receipt-24.png"))); // NOI18N
        jbtnPrescription.setText("Prescription");
        jbtnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrescriptionActionPerformed(evt);
            }
        });

        jbtnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientPrescription/icons8-sum-32.png"))); // NOI18N
        jbtnAddNew.setText("AddNew");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbtnAddNew)
                .addGap(93, 93, 93)
                .addComponent(jbtnDelete)
                .addGap(101, 101, 101)
                .addComponent(jbtnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jbtnPrescription)
                .addGap(53, 53, 53)
                .addComponent(jbtnPrint)
                .addGap(81, 81, 81)
                .addComponent(jbtnExit)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDelete)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnPrint)
                    .addComponent(jbtnPrescription)
                    .addComponent(jbtnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1050, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MedName", "Dosage(mg)", "Appointment", "Fees", "Patient Name", "Patient ID", "Patient DOB", "Phone Number"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1050, 130));

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel5.setText("Medicine Type:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel6.setText("Dosage(mg):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel7.setText("Appointment:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel8.setText("Fees:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, -1));
        getContentPane().add(jtxtMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, -1));
        getContentPane().add(jtxtMedDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, -1));
        getContentPane().add(jtxtAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, -1));
        getContentPane().add(jtxtFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 150, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel9.setText("Patient Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 130, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel10.setText("Patient ID:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 130, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel11.setText("Date of Birth:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 130, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel12.setText("Mobile Number#");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 150, -1));
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 150, -1));
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, -1));
        getContentPane().add(jtxtPatientDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 150, -1));
        getContentPane().add(jtxtPatientMobNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 150, -1));

        jcmbMedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Syrup", "Tablet", "Capsule" }));
        getContentPane().add(jcmbMedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel13.setText("Medicine Name:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, -1));

        jMenu1.setText("File");

        jMenuItemLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doctor/icons8_login_15px.png"))); // NOI18N
        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogin);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icons8_Logout_15px.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemReset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icons8_reset_15px_1.png"))); // NOI18N
        jMenuItemReset.setText("Reset");
        jMenuItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemReset);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pharmacy/icons8_about_15px.png"))); // NOI18N
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame=new JFrame();
        
        if(JOptionPane.showConfirmDialog(frame,"confirm if you want to exit?","Hospital Management System",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
           DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
           if(jTable1.getSelectedRow()==-1){
                if(jTable1.getRowCount()==0){
                    JOptionPane.showMessageDialog(null,"No data to delete","Hospital Management Systems",JOptionPane.OK_OPTION);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Select a row to delete","Hospital Management Systems",JOptionPane.OK_OPTION);
                }
           }
           else{
               model.removeRow(jTable1.getSelectedRow());
           }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jcmbMedType.getModel().setSelectedItem("Make a Selection");
        jtxtMedName.setText("");
        jtxtMedDose.setText("");
        jtxtAppointment.setText("");
        jtxtFees.setText("");
        jtxtPatientName.setText("");
        jtxtPatientMobNumber.setText("");
        jtxtPatientID.setText("");
        jtxtPatientDOB.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
    
        try{
            jtxtPrescription.print();
        }catch(PrinterException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrescriptionActionPerformed
        
        String qty1=(jtxtMedName.getText());
        String qty2=(jtxtMedDose.getText());
        String qty3=(jtxtAppointment.getText());
        String qty4=(jtxtFees.getText());
        String qty5=(jtxtPatientName.getText());
        String qty6=(jtxtPatientMobNumber.getText());
        String qty7=(jtxtPatientID.getText());
        String qty8=(jtxtPatientDOB.getText());
        String qty9=("");
        
        if(jcmbMedType.getSelectedItem().equals("Syrup")){
            qty9="Syrup";
        }
        else if(jcmbMedType.getSelectedItem().equals("Tablet")){
            qty9="Tablet";
        }
        else if(jcmbMedType.getSelectedItem().equals("Capsule")){
            qty9="Capsule";
        }
        jtxtPrescription.setText("");
        jtxtPrescription.append("\t*****Hospital Management System*****\n"
        +"\nPatient Name:\t\t"+qty5
        +"\nDate of Birth:\t\t"+qty8
        +"\nPatient ID:\t\t"+qty7
        +"\nPrescription:\t\t"+qty9
        +"\nMedicine Name:\t"+qty1
        +"\nMedicine Dose(mg):\t"+qty2
        +"\nFees:\t\t"+qty4
        +"\nAppointment:\t\t"+qty3);
    }//GEN-LAST:event_jbtnPrescriptionActionPerformed

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewActionPerformed
        // TODO add your handling code here:
        //DATABASE CODE WHICH IS WORKING PARTIALLY
//        try{
//            Class.forName("com.mysql.jdbc.Driver");
//            sqlcon=DriverManager.getConnection(dataconn,username,password);
//            pst=sqlcon.prepareStatement("insert into patientprescription(patientID,MedName,MedDose,IssueDate,ExpiryDate,PatientName,PatientDOB,"
//                    + "PatientPhoneNumber)value(?,?,?,?,?,?,?,?)");
//        
//            pst.setString(1, jtxtPatientID.getText());
//            pst.setString(2, jtxtMedName.getText());
//            pst.setString(3, jtxtMedDose.getText());
//            pst.setString(4, jtxtIssueDate.getText());
//            pst.setString(5, jtxtExpiryDate.getText());
//            pst.setString(6, jtxtPatientName.getText());
//            pst.setString(7, jtxtPatientDOB.getText());
//            pst.setString(8, jtxtPatientMobNumber.getText());
//            
//            pst.executeUpdate();
//            JOptionPane.showMessageDialog(this, "Record Added");
//            upDateDB();
//            
//            
//        } catch(ClassNotFoundException e){
//            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
//        } catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//========================================================================================================================================================
           
        if(jcmbMedType.getSelectedItem().toString().equals("Make a Selection")||jtxtMedName.getText().equals("")||jtxtMedDose.getText().equals("")
           ||jtxtAppointment.getText().equals("")||jtxtFees.getText().equals("")||jtxtPatientName.getText().equals("")
           ||jtxtPatientID.getText().equals("")||jtxtPatientDOB.getText().equals("")||jtxtPatientMobNumber.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"It is mandatory to fill all the fields","Hospital Management Systems",JOptionPane.OK_OPTION);
        }
        else
        {
           DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
           model.addRow(new Object[]{jtxtMedName.getText(),jtxtMedDose.getText(),jtxtAppointment.getText(),jtxtFees.getText(), jtxtPatientName.getText(),
                jtxtPatientID.getText(), jtxtPatientDOB.getText(), jtxtPatientMobNumber.getText()}); 
        }
 
    }//GEN-LAST:event_jbtnAddNewActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        // TODO add your handling code here:
//        ========================================================================================================================
//        DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
//            int SelectedRows=jTable1.getSelectedColumn();
//            
//            jtxtPatientID.setText(RecordTable.getValueAt(SelectedRows,1).toString());
//            jtxtMedName.setText(RecordTable.getValueAt(SelectedRows,2).toString());
//            jtxtMedDose.setText(RecordTable.getValueAt(SelectedRows,3).toString());
//            jtxtIssueDate.setText(RecordTable.getValueAt(SelectedRows,4).toString());
//            jtxtExpiryDate.setText(RecordTable.getValueAt(SelectedRows,5).toString());        
//            jtxtPatientName.setText(RecordTable.getValueAt(SelectedRows,6).toString());
//            jtxtPatientDOB.setText(RecordTable.getValueAt(SelectedRows,7).toString());
//            jtxtPatientMobNumber.setText(RecordTable.getValueAt(SelectedRows,8).toString());
//            
//           ================================================================================================================== 
//           TRYING TO FETCH THE DATA FROM THE DATABASE WHICH IS ALSO NOT WORKING
//            
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        // TODO add your handling code here:
        Login ilogin=new Login();
        ilogin.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(frame,"confirm if you want to exit?","Hospital Management System",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
        new about().setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResetActionPerformed
        // TODO add your handling code here:
        jcmbMedType.getModel().setSelectedItem("Make a Selection");
        jtxtMedName.setText("");
        jtxtMedDose.setText("");
        jtxtAppointment.setText("");
        jtxtFees.setText("");
        jtxtPatientName.setText("");
        jtxtPatientMobNumber.setText("");
        jtxtPatientID.setText("");
        jtxtPatientDOB.setText("");
    }//GEN-LAST:event_jMenuItemResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPrescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddNew;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrescription;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JComboBox<String> jcmbMedType;
    private javax.swing.JTextField jtxtAppointment;
    private javax.swing.JTextField jtxtFees;
    private javax.swing.JTextField jtxtMedDose;
    private javax.swing.JTextField jtxtMedName;
    private javax.swing.JTextField jtxtPatientDOB;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientMobNumber;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextArea jtxtPrescription;
    // End of variables declaration//GEN-END:variables
}
